runtime: custom
env: flex
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['FROM', 'python:3.7']
- name: 'gcr.io/cloud-builders/docker'
  args: ['WORKDIR', '/app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['COPY', 'requirements.txt', './requirements.txt']
- name: 'gcr.io/cloud-builders/docker'
  args: ['RUN', 'pip3', 'install', '-r', 'requirements.txt']
- name: 'gcr.io/cloud-builders/docker'
  args: ['EXPOSE', '8080']
- name: 'gcr.io/cloud-builders/docker'
  args: ['COPY', '.', '/app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['CMD', 'streamlit', 'run', '--server.port', '8080', '--server.enableCORS', 'false', 'Doku_main.py']