runtime: python37
env: flex
steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['RUN', 'pip3', 'install', '-r', 'requirements.txt']
entrypoint: streamlit run --server.port 8080 --server.enableCORS false main.py

